# This is a basic workflow to help you get started with Actions

name: Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package:
    name: Create TCZ pkg
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Package hab-server into TCZ pkg
      - name: Packaging
        run: |
          cd ./firmware/NOKHAB/hab-server

          mkdir -p build/usr/local/bin
          echo "#!/bin/sh" >> build/usr/local/bin/hab-server
          echo "/usr/local/bin/python3 /usr/local/share/hab-server/hab-server.py" >> build/usr/local/bin/hab-server
          mkdir -p build/usr/local/etc/init.d
          mkdir -p build/usr/local/share/hab-server
          find . -name \*.py -exec cp {} build/usr/local/share/hab-server \;
          mkdir -p build/usr/local/tce.installed
          echo "#!/bin/sh" >> build/usr/local/tce.installed/hab-server
          echo "/usr/local/etc/init.d/hab-server start" >> build/usr/local/tce.installed/hab-server
          
          mksquashfs build hab-server.tcz

  upload:
    name: Upload TCZ pkg
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Uploading
        uses: actions/upload-artifact@v2
        with:
          name: hab-server
          path: firmware/NOKHAB/hab-server/hab-server.tcz
    
